  version: '3'
  services:
    server:
      container_name: server
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SPRING_APPLICATION_JSON: >
          {
            "db": {
              "h2": true,
              "schema": true,
              "seed": true,
              "populate": true
            }
          }
      ports:
        - 8080:8080