spring:
  datasource:
    url: jdbc:h2:file:D:/DataBaseH2/data/SistemaInventario
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:clasificacion_activo.sql

